### ISSUE TITLE
Too many backtracks counted in solver statistics

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#102]
We report numbers of backtracks and backjumps in solver statistics (cf. #100). The problem is that the number of backtracks also increases when a backjump is made, because `DefaultSolver#backjump(int)` calls `backtrackFast()` internally. In my opinion, backtracks should not be counted during a backjump. @AntoniusW @lorenzleutgeb do you agree, or am I overlooking something? Should there be any counting-related difference between fast and slow backtracks?

**Comment by AntoniusW** [comment]
I guess it depends on what you understand by backtrack. Your reading of backtrack seems to be "backtrack=chronological backtrack in contrast to non-chronological backjump". The solver reads it as "backtrack=decision level that was removed". I currently have no preference for either, maybe also both interpretations are valuable and a new counter is fitting?

**Comment by rtaupe** [comment]
Good idea to include both numbers. This is implemented in 12d5fac143806825b44a32979bbc60bf16ce2cfa. When fixing #113, we can include three numbers in a nice format (total number of backtracks, those within backjumps, those outside backjumps).
