### ISSUE TITLE
Run (some) tests with internal checks enabled.

### ISSUE THREAD

**Issue by AntoniusW** [alpha-asp/Alpha#104]
In the past we discovered several bugs only by running with the time-consuming internal checks enabled and we have several example programs that triggered those issues (e.g. in #101). In order to avoid regressions, I think it would make sense to have those programs running with internal checks enabled in our CI test suite.

Note that it is not so much important that Alpha computes the correct answer sets for those programs, but that it runs without violating any of the checks. These kind of tests do not fit well into our current test layout, but I think it would make a valuable contribution and hence I would like to have a place to put them.

**Comment by rtaupe** [comment]
Aren´t currently all unit tests run with internal checks activated?
https://github.com/alpha-asp/Alpha/blob/ecd354a79cafe45c9ed8e3a649c8f0920f8aafc6/src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java#L103

**Comment by AntoniusW** [comment]
Oh, I was not aware of that. Good!

**Comment by rtaupe** [comment]
@AntoniusW can this issue be closed?
