### ISSUE TITLE
NaiveGrounder#groundAtomToString and NoGoodGenerator#collectNeg implicitly assume that BasicAtom#substitute forgets negatedness

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#119]
As of now, `BasicAtom.substitute(Substitution)` does not copy the value of the `negated` member variable to the new `BasicAtom` instance, which contradicts expected behaviour (#117).
However, both `NaiveGrounder#groundAtomToString` and `NoGoodGenerator#collectNeg` implicitly assume that `BasicAtom#substitute` forgets negatedness, so they too have to be fixed when #117 is fixed.

**Comment by AntoniusW** [comment]
I don't see where `NoGoodGenerator#collectNeg` is assuming that? Given that `BasicAtom#equals` is ignoring whether the atom it is negated, I think it should be fine.

**Comment by rtaupe** [comment]
It passes `groundAtom` to `AtomStore#add`. I guess this should only be done with positive atoms, right?

**Comment by AntoniusW** [comment]
Oh right, then the negated one is stored in `AtomStore`. My local fix added a `BasicAtom#getPositiveVersion` returning the positive equivalent of an atom and that was used inside `AtomStore#add`. This feels a bit wrong, however, and I'd like to see a better solution.
