### ISSUE TITLE
Make this repository citable

### ISSUE THREAD

**Issue by lorenzleutgeb** [alpha-asp/Alpha#147]
I would like to ease citation of what is going on in here, by following the steps described in [GitHub's Making Your Code Citable" guide](https://guides.github.com/activities/citable-code/).

The benefit is that every release in this repo will get a DOI that we can then refer to. Also, I do not expect any overhead. We should tag and release these versions anyway, and the rest of the workflow is fully automated. See an example: https://zenodo.org/record/1254325

Please raise objections, otherwise I will go forward ASAP.

/cc @AntoniusW @rtaupe

**Comment by AntoniusW** [comment]
Looks good, go ahead!

**Comment by AntoniusW** [comment]
... and maybe we should use this opportunity to release a new version of Alpha, it's been over a year since the last release and a lot has happened in the master branch.

**Comment by lorenzleutgeb** [comment]
Yep, I think so too. 86121a2 should be fine, right?

**Comment by AntoniusW** [comment]
Indeed, I suggest a version number of 0.3.0.

**Comment by lorenzleutgeb** [comment]
We're live as `v0.3.0` via https://doi.org/10.5281/zenodo.1418964 :)

Just so you know, there's some degrees of freedom in the Zenodo web-interface. If you feel that some information is missing/wrong, please ping me.

We'll get a new DOI automatically for every release. The shield in `README.md` will always show the most recent one. And there is a general, fixed DOI, which dynamically resolves to the latest version https://doi.org/10.5281/zenodo.1418963
