### ISSUE TITLE
Alpha ignores second input file if -i is missing

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#162]
If a user accidentally calls `java -jar Alpha.jar -i program.asp instance.asp` instead of `java -jar Alpha.jar -i program.asp -i instance.asp`, the input from `instance.asp` is silently ignored.

**Comment by AntoniusW** [comment]
Issue should be resolved now, thanks to #164. Please confirm whether this is the case @rtaupe. Thanks.

**Comment by rtaupe** [comment]
Fixed by e51364e7a9ec7f1e4792236609c698b92e353a05. Thanks @madmike200590!
