### ISSUE TITLE
Performance logs: time mistakenly reset when answer set is found

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#166]
After an answer set has been found, the time passed but not the number of decisions used to compute performance logs is reset. This means that the overall number of decisions is divided by the time that has passed since the last answer set has been found, which does not make sense.

**Comment by AntoniusW** [comment]
Agreed, this should be fixed. Since the this performance metric is not intended to only cover one answer set, but overall decisions, the "Decisions in x seconds" should be indifferent to whether (some) answer sets have been found in those x seconds.
