### ISSUE TITLE
Filter settings ignored

### ISSUE THREAD

**Issue by AntoniusW** [alpha-asp/Alpha#189]
If a filter is given with `-f pred` on the commandline, this information is not passed to the grounder, i.e., no filters are applied currently. The culprit seems to be in line 120 of `Alpha.java` where the grounder instance is created with default (i.e., no) filters set.

Seems to be a bug introduced by the recent refactoring.

**Comment by madmike200590** [comment]
Fixed in PR #190

**Comment by AntoniusW** [comment]
Fixed by #190
