### ISSUE TITLE
adapt gradle build to be able to install Alpha into the local maven repository

### ISSUE THREAD

**Issue by madmike200590** [alpha-asp/Alpha#208]
In order to make using Alpha from other (java-)applications easier, it should be possible to install the Alpha.jar to the local maven repository (```~/.m2/repository```). By having the alpha jar in the local maven repo, one could easily add Alpha as a dependency to a maven project without having to manually copy around jar files, e.g.:
```
<dependencies>
    <dependency>
        <groupId>io.github.alpha-asp</groupId>
        <artifactId>alpha</artifactId>
        <version>0.2.0</version>
    </dependency>
</dependencies>
```
Could be easily realized using gradle's publishing plugin (https://docs.gradle.org/current/userguide/publishing_maven.html).
This is also a necessary precondition to realizing #148.

**Comment by lorenzleutgeb** [comment]
Yes, that's easy, but please read the deprecation note on the page you linked and use https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven instead.
