### ISSUE TITLE
Formatting error when printing value for `Overall replayed assignments:`

### ISSUE THREAD

**Issue by KillerLink** [alpha-asp/Alpha#258]
In the picture below you can see that the value printed after `Overall replayed assignments: `
 -  is negative, despite expected to be positve
 - decreasing in absolute value, despite expected to be increasing in absolute value

The symptons suggest that there seems might be adiscrepancy between the internal datatype and the formating used to print to console of the value printed after . Looks like a `long interger` internally that is printed as if it was an `integer`.

![image](https://user-images.githubusercontent.com/17423668/87034715-9aafb000-c1e8-11ea-8bd5-8f256354f34a.png)

**Comment by madmike200590** [comment]
Thanks a lot for bringing  this up! Since I strongly suspect this is just a logging issue, I think this can be fixed quickly

**Comment by AntoniusW** [comment]
The issue should be resolved by PR #261 . If the problem still persists, please provide us with more information (e.g., the program causing the issue).
