### ISSUE TITLE
Interval rewriting failing on negative integer literals

### ISSUE THREAD

**Issue by madmike200590** [alpha-asp/Alpha#292]
pending further analysis

**Comment by AntoniusW** [comment]
Do we have more information on this, or some kind of example demonstrating the issue?

**Comment by madmike200590** [comment]
The simple example I noticed it on is just any fact with an interval like `values(-3..3)`, i.e. an interval with a negative integer.
I still need to do some further analysis, but suspect that `ArithmeticTermRewriting` and `IntervalRewriting` get into each other's way in some fashion.
