### ISSUE TITLE
ASP directive #show

### ISSUE THREAD

**Issue by hmqq** [alpha-asp/Alpha#294]
Hello,

Does Alpha support ASP directive e.g. #show?

**Comment by AntoniusW** [comment]
Hi hmqq,

Alpha does currently not support a #show directive. It does, however, support a command-line argument `-f` or `--filter` which has a similar effect as #show has in other ASP systems. It projects answer-sets to only those predicates that are filtered. For example, if you want to see only predicates `foo` and `bar` just add `-f foo -f bar` to your command-line arguments.

**Comment by hmqq** [comment]
Okay it worked. Thankyou
