### ISSUE TITLE
Build broken (Gradle version and JAVA updates)

### ISSUE THREAD

**Issue by AntoniusW** [alpha-asp/Alpha#350]
It appears that merging #349 broke our CI builds.

After pushing the new branch "ruleatom_nostring" (based on current master), the CI build immediately fails, see:
https://github.com/alpha-asp/Alpha/actions/runs/3822262718

The error message is:
```
Could not compile initialization script '/home/runner/.gradle/init.d/build-result-capture.init.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
```
According to https://docs.gradle.org/current/userguide/compatibility.html Java 19 is only supported after Gradle version 7.6 while we currently run at 7.3.2 for the CI builds.

Interestingly, the build job for #349 apparently succeeded with the Java 19 run throwing some exceptions but still succeeding:
https://github.com/alpha-asp/Alpha/actions/runs/3668635491/jobs/6201900714

It appears that the currently failing branch tried to start with Java 19 and failed while the CI run for #349 used Gradle caching to obtain the already compiled Gradle build system. Could this have something to do with Gradle's caching?

**Comment by madmike200590** [comment]
From the top of my head, I'd say the best and easiest fix for this is to bump the gradle version to 7.6.
I'll take care of that tonight.

**Comment by lorenzleutgeb** [comment]
Sorry about that. Super weird that #349 did build green.
