### ISSUE TITLE
missing answer set

### ISSUE THREAD

**Issue by tobiaskaminski** [alpha-asp/Alpha#45]
For the following program, Alpha outputs three answer sets:

```
assign(L, R) :- not nassign(L, R), possible(L, R).
nassign(L, R) :- not assign(L, R), possible(L, R).

assigned(L) :- assign(L, R).
:- possible(L,_), not assigned(L).
:- assign(L, R1), assign(L, R2), R1 != R2.

possible(l1, r1). possible(l3, r3). possible(l4, r1). possible(l4, r3). possible(l5, r4). possible(l6, r2). possible(l7, r3). possible(l8, r2). possible(l9, r1). possible(l9, r4).
```

The answer sets with `--filter assign` are:
```
{assign(l9,r4),assign(l8,r2),assign(l7,r3),assign(l6,r2),assign(l5,r4),assign(l4,r3),assign(l3,r3),assign(l2,r2),assign(l1,r1)}
{assign(l9,r1),assign(l8,r2),assign(l7,r3),assign(l6,r2),assign(l5,r4),assign(l4,r3),assign(l3,r3),assign(l2,r2),assign(l1,r1)}
{assign(l9,r1),assign(l8,r2),assign(l7,r3),assign(l6,r2),assign(l5,r4),assign(l4,r1),assign(l3,r3),assign(l2,r2),assign(l1,r1)}
```
None of the three answer sets contains `assign(l9,r4)` and `assign(l4,r1)` simultaneously. However, when I add the following two constraints
```
:- not assign(l9,r4).
:- not assign(l4,r1).
```
the following answer set is output:

```{assign(l9,r4),assign(l4,r1),assign(l8,r2),assign(l7,r3),assign(l6,r2),assign(l5,r4),assign(l3,r3),assign(l2,r2),assign(l1,r1)}```

The latter answer set contains  `assign(l9,r4)` and `assign(l4,r1)`, even though constraints should only delete answer sets.

**Comment by tobiaskaminski** [comment]
Does it maybe have to do with the use of the "!="-operator?

**Comment by AntoniusW** [comment]
Added a test for the above program in 3f6f68a. The issue seems to be resolved now.
