### ISSUE TITLE
Represent builtin-atom with its own class.

### ISSUE THREAD

**Issue by AntoniusW** [alpha-asp/Alpha#69]
Currently, the builtin atoms (according to the standard) are internally represented by an `ExternalAtom`. I think it would be better to represent them by their own atom class, e.g. `BuiltinAtom` or `ComparisonAtom`. There are two reasons: first, it feels more natural than representing them with `ExternalAtom`, and second, these builtin atoms can bind variables (according to the standard) but it depends on the actual instance of the atom. If the comparison operator is `=` and on one side there is a single variable, then this variable is binding. So, `X = Y + 3` would have `X` binding and `Y` non-binding while for `X +1 = Y` it would be the other way round. I think this behaviour cannot be modelled with `ExternalAtom` in a nice way.

Are there any arguments against introducing this new atom class?

**Comment by lorenzleutgeb** [comment]
No, I think that's a good idea. my only concern is that we might need code very similar to `BuiltinBiPredicate`. Let's see how it goes.

**Comment by AntoniusW** [comment]
Yes, this would supersede `BuiltinBiPredicate` and the new class would use some of its code.

**Comment by lorenzleutgeb** [comment]
OK

**Comment by AntoniusW** [comment]
Resolved with #88 merged.
