### ISSUE TITLE
Move Alpha to a new non-personal namespace

### ISSUE THREAD

**Issue by lorenzleutgeb** [alpha-asp/Alpha#8]
As we now have approx. four contributors, I think that Alpha has grown beyond the scope of @AntoniusW. I suggest creating a new organization and moving Alpha over. All contributors to the project should be members of that organization and given push access to the repository.

**Comment by AntoniusW** [comment]
I think this issue is resolved for quite some time now. @lorenzleutgeb is there anything left to do?
