### ISSUE TITLE
Option to print statistics

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#99]
Currently, `DefaultSolver` logs brief statistics containing numbers of choices, backtracks etc. in `logStats()` by writing to a Logger on the Debug level. This has the disadvantage that the log level has to be changed in order to see the statistics. It would be better to have a command-line option called "stats" that activates printing the statistics, as in other ASP systems (e.g. [clingo](https://potassco.org/clingo/)).

**Comment by AntoniusW** [comment]
Sounds good.
